name: "Zombie Horde: Reloaded"
timezone: Australia/Sydney
  
collections:

disqus: 3pills
google_analytics: UA-63619308-2

url: http://www.zombiehorde-reloaded.com/
baseurl: ""

permalink: /:title

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

version: v1.1.0

sass:
  style: :expanded

gems:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME